pybo/views/answer_views.py
from datetime import datetime
from .auth_views import login_required
from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from .. import db
from ..forms import AnswerForm
from ..models import Question, Answer

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=answer.question.id))
    else:
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', form=form)

@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash('삭제권한이 없습니다')
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/views/question_views.py
import functools
from pybo.views.auth_views import login_required

from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from .. import db
from ..models import Question
from ..forms import QuestionForm, AnswerForm

bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)  # 페이지
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data,
                            create_date=datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':  # POST 요청
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:  # GET 요청
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)

@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))

pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='question_detail.css') }}">
<main>
    <h4 class="title_q">
      {{ question.subject }}
      {% if g.user == question.user %}
      <span class="my-3">
        <a href="{{ url_for('question.modify', question_id=question.id) }}"
            class="btn btn-sm btn-outline-secondary">수정</a>
        <a href="#" class="delete btn btn-sm btn-outline-secondary"
          data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
      </span>
      {% endif %}
    </h4>
    <h6>
      {{ question.create_date|datetime }} - {{ question.user.username }}
    </h6><hr>

    <div>
        <p>{{ question.content|markdown }}</p>
    </div><hr>

    <h5>댓글 {{ question.answer_set|length }}개</h5>
    
  <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->
      <textarea {% if not g.user %}disabled{% endif %} class="form-control" name="content" id="content" rows="3" placeholder="{{ g.user.username }}님의 댓글을 입력해 주세요&#13;&#10;비방,욕설 등이 포함된 댓글은 제제 대상이 될 수 있습니다"></textarea>
      <input class="btn btn-outline-primary" type="submit" value="답변등록">
  </form>

    <div class="answer">
        <ul class="list-group">
          {% for answer in question.answer_set %}
            <li class="list-group-item"> {{ answer.user.username }}님: {{ answer.content }}
              <span class="answer_info">
               - {{ answer.create_date|datetime }}
              </span>
              {% if g.user == answer.user %}
              <span class="my-3">
                  <a href="{{ url_for('answer.modify', answer_id=answer.id) }}" class="edit_answer">수정</a>
                  <a href="{{ url_for('answer.delete', answer_id=answer.id) }}" class="delete_answer">삭제</a>
              </span>
              {% endif %}
              {% if g.user == answer.user %}
              {% endif %}
            </li>
          {% endfor %}
        </ul>
    </div>
</main>
<footer>
  Copyright &copy; 2022. All rights reserved.
</footer>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='question_form.css') }}">
<main>
<form method="post" class="post-form my-3">
    {{ form.csrf_token }}
    <!-- 오류표시 Start -->
    {% for field, errors in form.errors.items() %}
    <div class="alert alert-danger" role="alert">
        <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
    </div>
    {% endfor %}
    <!-- 오류표시 End -->
    <div class="form-group">
        <label for="subject"></label>
        <input type="text" class="form-control" name="subject" id="subject" placeholder="제목을 입력하세요"
        value="{{ form.subject.data or '' }}">
    </div>
    <h6>20xx.xx.xx - {{ g.user.username }}</h6><hr>
    <div class="form-group">
        <label for="content"></label>
        <textarea class="form-control" name="content" id="content" rows="5" placeholder="내용을 입력하세요">{{ form.content.data or '' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary" id="save">저장하기</button>
    <a type="button" href="{{ url_for('main.index') }}" class="btn btn-secondary" id="can">취소</a>
    <hr>
    <h5>댓글 3개</h5>
    <div class="answer">
        <ul class="list-group">
            <li class="list-group-item">댓글 미리보기 입니다</li>
            <li class="list-group-item">댓글 미리보기 입니다</li>
            <li class="list-group-item">댓글 미리보기 입니다</li>
        </ul>
    </div>
</form>
</main>
<footer>
Copyright &copy; 2022. All rights reserved.
</footer>
{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container my-3">
        <table class="table">
            <thead>
                <tr class="text-center thead-dark">
                    <th>번호</th>
                    <th style="width:50%">제목</th>
                    <th>글쓴이</th>
                    <th>작성일시</th>
                </tr>
            </thead>
            <tbody>
            {% if question_list %}
            {% for question in question_list.items %}
            <tr class="text-center">
                <td>{{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}</td>
                <td class="text-left">
                    <a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
                    {% if question.answer_set|length > 0 %}
                    <span class="text-primary small ml-2">{{ question.answer_set|length }}</span>
                    {% endif %}
                </td>
                <td>{{ question.user.username }}</td>  <!-- 글쓴이 추가 -->
                <td>{{ question.create_date|datetime }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if question_list.has_prev %}
    <li class="page-item">
        <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
            {% if page_num != question_list.page %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
            {% else %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">{{ page_num }}</a>
            </li>
            {% endif %}
       {% else %}
            <li class="disabled">
                <a class="page-link" href="#">...</a>
            </li>
       {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
</ul>
<!-- 페이징처리 끝 -->
        <a href="{{ url_for('question.create') }}" class="btn btn-primary">글쓰기</a>
    </div>
{% endblock %}